/* eslint-disable quote-props */
const { Op } = require('../../database/dao');

const $Op = {
    '=': Op.eq,
    '!=': Op.ne,
    '>=': Op.gte,
    '>': Op.gt,
    '<=': Op.lte,
    '<': Op.lt,
    'not': Op.not,
    'in': Op.in,
    'notIn': Op.notIn,
    'is': Op.is,
    'like': Op.like,
    'notLike': Op.notLike,
    'iLike': Op.iLike,
    'notILike': Op.notILike,
    'regexp': Op.regexp,
    'notRegexp': Op.notRegexp,
    'iRegexp': Op.iRegexp,
    'notIRegexp': Op.notIRegexp,
    'between': Op.between,
    'notBetween': Op.notBetween,
    'overlap': Op.overlap,
    'contains': Op.contains,
    'contained': Op.contained,
    'adjacent': Op.adjacent,
    'strictLeft': Op.strictLeft,
    'strictRight': Op.strictRight,
    'noExtendRight': Op.noExtendRight,
    'noExtendLeft': Op.noExtendLeft,
    'and': Op.and,
    'or': Op.or,
    'any': Op.any,
    'all': Op.all,
    'values': Op.values,
    'col': Op.col,
};

module.exports = $Op;
